[package]
name = "mark_last"
description = "Simple extension to rust iterator's to mark the last element of an iterator"
version = "0.9.2"
authors = ["Marcus Svensson <marcus@lincopia.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/mrcz/mark_last/"
